// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcp/v1alpha1/mcp.proto

package v1alpha1 // import "github.com/f4tq/istio-api-mod/mcp/v1alpha1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/rpc"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for SinkNode
func (this *SinkNode) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for SinkNode
func (this *SinkNode) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for SinkNode_AnnotationsEntry
func (this *SinkNode_AnnotationsEntry) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for SinkNode_AnnotationsEntry
func (this *SinkNode_AnnotationsEntry) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for MeshConfigRequest
func (this *MeshConfigRequest) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for MeshConfigRequest
func (this *MeshConfigRequest) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for MeshConfigResponse
func (this *MeshConfigResponse) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for MeshConfigResponse
func (this *MeshConfigResponse) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for IncrementalMeshConfigRequest
func (this *IncrementalMeshConfigRequest) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for IncrementalMeshConfigRequest
func (this *IncrementalMeshConfigRequest) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for IncrementalMeshConfigRequest_InitialResourceVersionsEntry
func (this *IncrementalMeshConfigRequest_InitialResourceVersionsEntry) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for IncrementalMeshConfigRequest_InitialResourceVersionsEntry
func (this *IncrementalMeshConfigRequest_InitialResourceVersionsEntry) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for IncrementalMeshConfigResponse
func (this *IncrementalMeshConfigResponse) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for IncrementalMeshConfigResponse
func (this *IncrementalMeshConfigResponse) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for RequestResources
func (this *RequestResources) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for RequestResources
func (this *RequestResources) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for RequestResources_InitialResourceVersionsEntry
func (this *RequestResources_InitialResourceVersionsEntry) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for RequestResources_InitialResourceVersionsEntry
func (this *RequestResources_InitialResourceVersionsEntry) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Resources
func (this *Resources) MarshalJSON() ([]byte, error) {
	str, err := McpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Resources
func (this *Resources) UnmarshalJSON(b []byte) error {
	return McpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	McpMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	McpUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
