// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcp/v1alpha1/metadata.proto

package v1alpha1 // import "github.com/f4tq/istio-api-mod/mcp/v1alpha1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for Metadata
func (this *Metadata) MarshalJSON() ([]byte, error) {
	str, err := MetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Metadata
func (this *Metadata) UnmarshalJSON(b []byte) error {
	return MetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Metadata_LabelsEntry
func (this *Metadata_LabelsEntry) MarshalJSON() ([]byte, error) {
	str, err := MetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Metadata_LabelsEntry
func (this *Metadata_LabelsEntry) UnmarshalJSON(b []byte) error {
	return MetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Metadata_AnnotationsEntry
func (this *Metadata_AnnotationsEntry) MarshalJSON() ([]byte, error) {
	str, err := MetadataMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Metadata_AnnotationsEntry
func (this *Metadata_AnnotationsEntry) UnmarshalJSON(b []byte) error {
	return MetadataUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	MetadataMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	MetadataUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
