// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/v1/attributes.proto

package v1 // import "github.com/f4tq/istio-api-mod/mixer/v1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for Attributes
func (this *Attributes) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Attributes
func (this *Attributes) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Attributes_AttributesEntry
func (this *Attributes_AttributesEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Attributes_AttributesEntry
func (this *Attributes_AttributesEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Attributes_AttributeValue
func (this *Attributes_AttributeValue) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Attributes_AttributeValue
func (this *Attributes_AttributeValue) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Attributes_StringMap
func (this *Attributes_StringMap) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Attributes_StringMap
func (this *Attributes_StringMap) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Attributes_StringMap_EntriesEntry
func (this *Attributes_StringMap_EntriesEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Attributes_StringMap_EntriesEntry
func (this *Attributes_StringMap_EntriesEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes
func (this *CompressedAttributes) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes
func (this *CompressedAttributes) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_StringsEntry
func (this *CompressedAttributes_StringsEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_StringsEntry
func (this *CompressedAttributes_StringsEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_Int64SEntry
func (this *CompressedAttributes_Int64SEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_Int64SEntry
func (this *CompressedAttributes_Int64SEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_DoublesEntry
func (this *CompressedAttributes_DoublesEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_DoublesEntry
func (this *CompressedAttributes_DoublesEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_BoolsEntry
func (this *CompressedAttributes_BoolsEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_BoolsEntry
func (this *CompressedAttributes_BoolsEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_TimestampsEntry
func (this *CompressedAttributes_TimestampsEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_TimestampsEntry
func (this *CompressedAttributes_TimestampsEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_DurationsEntry
func (this *CompressedAttributes_DurationsEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_DurationsEntry
func (this *CompressedAttributes_DurationsEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_BytesEntry
func (this *CompressedAttributes_BytesEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_BytesEntry
func (this *CompressedAttributes_BytesEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CompressedAttributes_StringMapsEntry
func (this *CompressedAttributes_StringMapsEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CompressedAttributes_StringMapsEntry
func (this *CompressedAttributes_StringMapsEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for StringMap
func (this *StringMap) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for StringMap
func (this *StringMap) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for StringMap_EntriesEntry
func (this *StringMap_EntriesEntry) MarshalJSON() ([]byte, error) {
	str, err := AttributesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for StringMap_EntriesEntry
func (this *StringMap_EntriesEntry) UnmarshalJSON(b []byte) error {
	return AttributesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	AttributesMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	AttributesUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
