// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authentication/v1alpha1/policy.proto

package v1alpha1 // import "github.com/f4tq/istio-api-mod/authentication/v1alpha1"

/*
This package defines user-facing authentication policy.
*/

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for StringMatch
func (this *StringMatch) MarshalJSON() ([]byte, error) {
	str, err := PolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for StringMatch
func (this *StringMatch) UnmarshalJSON(b []byte) error {
	return PolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for PeerAuthenticationMethod
func (this *PeerAuthenticationMethod) MarshalJSON() ([]byte, error) {
	str, err := PolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for PeerAuthenticationMethod
func (this *PeerAuthenticationMethod) UnmarshalJSON(b []byte) error {
	return PolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for PortSelector
func (this *PortSelector) MarshalJSON() ([]byte, error) {
	str, err := PolicyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for PortSelector
func (this *PortSelector) UnmarshalJSON(b []byte) error {
	return PolicyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	PolicyMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	PolicyUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
