// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/adapter/model/v1beta1/check.proto

package v1beta1 // import "github.com/f4tq/istio-api-mod/mixer/adapter/model/v1beta1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/rpc"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for CheckResult
func (this *CheckResult) MarshalJSON() ([]byte, error) {
	str, err := CheckMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CheckResult
func (this *CheckResult) UnmarshalJSON(b []byte) error {
	return CheckUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CheckMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	CheckUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
