// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/adapter/model/v1beta1/infrastructure_backend.proto

package v1beta1 // import "github.com/f4tq/istio-api-mod/mixer/adapter/model/v1beta1"

/*
This package defines the service and types used by adapter code to serve requests from Mixer.
This package also defines the types that are used to create Mixer templates.
*/

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/rpc"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for CreateSessionRequest
func (this *CreateSessionRequest) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CreateSessionRequest
func (this *CreateSessionRequest) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CreateSessionRequest_InferredTypesEntry
func (this *CreateSessionRequest_InferredTypesEntry) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CreateSessionRequest_InferredTypesEntry
func (this *CreateSessionRequest_InferredTypesEntry) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CreateSessionResponse
func (this *CreateSessionResponse) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CreateSessionResponse
func (this *CreateSessionResponse) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for ValidateRequest
func (this *ValidateRequest) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for ValidateRequest
func (this *ValidateRequest) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for ValidateRequest_InferredTypesEntry
func (this *ValidateRequest_InferredTypesEntry) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for ValidateRequest_InferredTypesEntry
func (this *ValidateRequest_InferredTypesEntry) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for ValidateResponse
func (this *ValidateResponse) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for ValidateResponse
func (this *ValidateResponse) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CloseSessionRequest
func (this *CloseSessionRequest) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CloseSessionRequest
func (this *CloseSessionRequest) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for CloseSessionResponse
func (this *CloseSessionResponse) MarshalJSON() ([]byte, error) {
	str, err := InfrastructureBackendMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for CloseSessionResponse
func (this *CloseSessionResponse) UnmarshalJSON(b []byte) error {
	return InfrastructureBackendUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	InfrastructureBackendMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	InfrastructureBackendUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
