// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/adapter/model/v1beta1/quota.proto

package v1beta1 // import "github.com/f4tq/istio-api-mod/mixer/adapter/model/v1beta1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaRequest
func (this *QuotaRequest) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaRequest
func (this *QuotaRequest) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaRequest_QuotaParams
func (this *QuotaRequest_QuotaParams) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaRequest_QuotaParams
func (this *QuotaRequest_QuotaParams) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaRequest_QuotasEntry
func (this *QuotaRequest_QuotasEntry) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaRequest_QuotasEntry
func (this *QuotaRequest_QuotasEntry) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaResult
func (this *QuotaResult) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaResult
func (this *QuotaResult) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaResult_Result
func (this *QuotaResult_Result) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaResult_Result
func (this *QuotaResult_Result) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaResult_QuotasEntry
func (this *QuotaResult_QuotasEntry) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaResult_QuotasEntry
func (this *QuotaResult_QuotasEntry) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	QuotaMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	QuotaUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
