// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/adapter/model/v1beta1/template.proto

package v1beta1 // import "github.com/f4tq/istio-api-mod/mixer/adapter/model/v1beta1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for Template
func (this *Template) MarshalJSON() ([]byte, error) {
	str, err := TemplateMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Template
func (this *Template) UnmarshalJSON(b []byte) error {
	return TemplateUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	TemplateMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	TemplateUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
