// +build !ignore_autogenerated

// Copyright 2019 Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	rpc "github.com/gogo/googleapis/google/rpc"
	types "github.com/gogo/protobuf/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckResult) DeepCopyInto(out *CheckResult) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckResult.
func (in *CheckResult) DeepCopy() *CheckResult {
	if in == nil {
		return nil
	}
	out := new(CheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloseSessionRequest) DeepCopyInto(out *CloseSessionRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloseSessionRequest.
func (in *CloseSessionRequest) DeepCopy() *CloseSessionRequest {
	if in == nil {
		return nil
	}
	out := new(CloseSessionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloseSessionResponse) DeepCopyInto(out *CloseSessionResponse) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		if *in == nil {
			*out = nil
		} else {
			*out = new(rpc.Status)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloseSessionResponse.
func (in *CloseSessionResponse) DeepCopy() *CloseSessionResponse {
	if in == nil {
		return nil
	}
	out := new(CloseSessionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateSessionRequest) DeepCopyInto(out *CreateSessionRequest) {
	*out = *in
	if in.AdapterConfig != nil {
		in, out := &in.AdapterConfig, &out.AdapterConfig
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.Any)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.InferredTypes != nil {
		in, out := &in.InferredTypes, &out.InferredTypes
		*out = make(map[string]*types.Any, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = new(types.Any)
				val.DeepCopyInto((*out)[key])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSessionRequest.
func (in *CreateSessionRequest) DeepCopy() *CreateSessionRequest {
	if in == nil {
		return nil
	}
	out := new(CreateSessionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateSessionResponse) DeepCopyInto(out *CreateSessionResponse) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		if *in == nil {
			*out = nil
		} else {
			*out = new(rpc.Status)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSessionResponse.
func (in *CreateSessionResponse) DeepCopy() *CreateSessionResponse {
	if in == nil {
		return nil
	}
	out := new(CreateSessionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Info) DeepCopyInto(out *Info) {
	*out = *in
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Info.
func (in *Info) DeepCopy() *Info {
	if in == nil {
		return nil
	}
	out := new(Info)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaRequest) DeepCopyInto(out *QuotaRequest) {
	*out = *in
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = make(map[string]QuotaRequest_QuotaParams, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaRequest.
func (in *QuotaRequest) DeepCopy() *QuotaRequest {
	if in == nil {
		return nil
	}
	out := new(QuotaRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaRequest_QuotaParams) DeepCopyInto(out *QuotaRequest_QuotaParams) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaRequest_QuotaParams.
func (in *QuotaRequest_QuotaParams) DeepCopy() *QuotaRequest_QuotaParams {
	if in == nil {
		return nil
	}
	out := new(QuotaRequest_QuotaParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaResult) DeepCopyInto(out *QuotaResult) {
	*out = *in
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = make(map[string]QuotaResult_Result, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaResult.
func (in *QuotaResult) DeepCopy() *QuotaResult {
	if in == nil {
		return nil
	}
	out := new(QuotaResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaResult_Result) DeepCopyInto(out *QuotaResult_Result) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaResult_Result.
func (in *QuotaResult_Result) DeepCopy() *QuotaResult_Result {
	if in == nil {
		return nil
	}
	out := new(QuotaResult_Result)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportResult) DeepCopyInto(out *ReportResult) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportResult.
func (in *ReportResult) DeepCopy() *ReportResult {
	if in == nil {
		return nil
	}
	out := new(ReportResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Template) DeepCopyInto(out *Template) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Template.
func (in *Template) DeepCopy() *Template {
	if in == nil {
		return nil
	}
	out := new(Template)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateRequest) DeepCopyInto(out *ValidateRequest) {
	*out = *in
	if in.AdapterConfig != nil {
		in, out := &in.AdapterConfig, &out.AdapterConfig
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.Any)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.InferredTypes != nil {
		in, out := &in.InferredTypes, &out.InferredTypes
		*out = make(map[string]*types.Any, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = new(types.Any)
				val.DeepCopyInto((*out)[key])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateRequest.
func (in *ValidateRequest) DeepCopy() *ValidateRequest {
	if in == nil {
		return nil
	}
	out := new(ValidateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidateResponse) DeepCopyInto(out *ValidateResponse) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		if *in == nil {
			*out = nil
		} else {
			*out = new(rpc.Status)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidateResponse.
func (in *ValidateResponse) DeepCopy() *ValidateResponse {
	if in == nil {
		return nil
	}
	out := new(ValidateResponse)
	in.DeepCopyInto(out)
	return out
}
