// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1alpha3/gateway.proto

package v1alpha3 // import "github.com/f4tq/istio-api-mod/networking/v1alpha3"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// message: Gateway
// fieldName name:"servers" number:1 label:LABEL_REPEATED type:TYPE_MESSAGE type_name:".istio.networking.v1alpha3.Server" json_name:"servers"
// fieldName name:"selector" number:2 label:LABEL_REPEATED type:TYPE_MESSAGE type_name:".istio.networking.v1alpha3.Gateway.SelectorEntry" json_name:"selector"
// message: SelectorEntry
// fieldName name:"key" number:1 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"key"
// fieldName name:"value" number:2 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"value"
// message: Server
// fieldName name:"port" number:1 label:LABEL_OPTIONAL type:TYPE_MESSAGE type_name:".istio.networking.v1alpha3.Port" json_name:"port"
// fieldName name:"bind" number:4 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"bind"
// fieldName name:"hosts" number:2 label:LABEL_REPEATED type:TYPE_STRING json_name:"hosts"
// fieldName name:"tls" number:3 label:LABEL_OPTIONAL type:TYPE_MESSAGE type_name:".istio.networking.v1alpha3.Server.TLSOptions" json_name:"tls"
// fieldName name:"default_endpoint" number:5 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"defaultEndpoint"
// message: TLSOptions
// Generating Marshal for message: TLSOptions
// MarshalJSON is a custom marshaler supporting oneof fields for Server_TLSOptions
func (this *Server_TLSOptions) MarshalJSON() ([]byte, error) {
	str, err := GatewayMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Server_TLSOptions
func (this *Server_TLSOptions) UnmarshalJSON(b []byte) error {
	return GatewayUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// message: Port
// fieldName name:"number" number:1 label:LABEL_OPTIONAL type:TYPE_UINT32 json_name:"number"
// fieldName name:"protocol" number:2 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"protocol"
// fieldName name:"name" number:3 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"name"
var (
	GatewayMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	GatewayUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
