// +build !ignore_autogenerated

// Copyright 2019 Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	types "github.com/gogo/protobuf/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeManifest.
func (in *AttributeManifest) DeepCopy() *AttributeManifest {
	if in == nil {
		return nil
	}
	out := new(AttributeManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeManifest_AttributeInfo) DeepCopyInto(out *AttributeManifest_AttributeInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeManifest_AttributeInfo.
func (in *AttributeManifest_AttributeInfo) DeepCopy() *AttributeManifest_AttributeInfo {
	if in == nil {
		return nil
	}
	out := new(AttributeManifest_AttributeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	if in.AuthType == nil {
		out.AuthType = nil
	} else {
		out.AuthType = in.AuthType.DeepCopyisAuthentication_AuthType()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication_Mutual) DeepCopyInto(out *Authentication_Mutual) {
	*out = *in
	if in.Mutual != nil {
		in, out := &in.Mutual, &out.Mutual
		if *in == nil {
			*out = nil
		} else {
			*out = new(Mutual)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication_Mutual.
func (in *Authentication_Mutual) DeepCopy() *Authentication_Mutual {
	if in == nil {
		return nil
	}
	out := new(Authentication_Mutual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication_Tls) DeepCopyInto(out *Authentication_Tls) {
	*out = *in
	if in.Tls != nil {
		in, out := &in.Tls, &out.Tls
		if *in == nil {
			*out = nil
		} else {
			*out = new(Tls)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication_Tls.
func (in *Authentication_Tls) DeepCopy() *Authentication_Tls {
	if in == nil {
		return nil
	}
	out := new(Authentication_Tls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		if *in == nil {
			*out = nil
		} else {
			*out = new(time.Duration)
			**out = **in
		}
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		if *in == nil {
			*out = nil
		} else {
			*out = new(Authentication)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSName) DeepCopyInto(out *DNSName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSName.
func (in *DNSName) DeepCopy() *DNSName {
	if in == nil {
		return nil
	}
	out := new(DNSName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectHttpResponse) DeepCopyInto(out *DirectHttpResponse) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectHttpResponse.
func (in *DirectHttpResponse) DeepCopy() *DirectHttpResponse {
	if in == nil {
		return nil
	}
	out := new(DirectHttpResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Duration) DeepCopyInto(out *Duration) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.Duration)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Duration.
func (in *Duration) DeepCopy() *Duration {
	if in == nil {
		return nil
	}
	out := new(Duration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailAddress) DeepCopyInto(out *EmailAddress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailAddress.
func (in *EmailAddress) DeepCopy() *EmailAddress {
	if in == nil {
		return nil
	}
	out := new(EmailAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FractionalPercent) DeepCopyInto(out *FractionalPercent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FractionalPercent.
func (in *FractionalPercent) DeepCopy() *FractionalPercent {
	if in == nil {
		return nil
	}
	out := new(FractionalPercent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Handler.
func (in *Handler) DeepCopy() *Handler {
	if in == nil {
		return nil
	}
	out := new(Handler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAddress) DeepCopyInto(out *IPAddress) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAddress.
func (in *IPAddress) DeepCopy() *IPAddress {
	if in == nil {
		return nil
	}
	out := new(IPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mutual) DeepCopyInto(out *Mutual) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mutual.
func (in *Mutual) DeepCopy() *Mutual {
	if in == nil {
		return nil
	}
	out := new(Mutual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth) DeepCopyInto(out *OAuth) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EndpointParams != nil {
		in, out := &in.EndpointParams, &out.EndpointParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth.
func (in *OAuth) DeepCopy() *OAuth {
	if in == nil {
		return nil
	}
	out := new(OAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomSampling) DeepCopyInto(out *RandomSampling) {
	*out = *in
	if in.PercentSampled != nil {
		in, out := &in.PercentSampled, &out.PercentSampled
		if *in == nil {
			*out = nil
		} else {
			*out = new(FractionalPercent)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomSampling.
func (in *RandomSampling) DeepCopy() *RandomSampling {
	if in == nil {
		return nil
	}
	out := new(RandomSampling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitSampling) DeepCopyInto(out *RateLimitSampling) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitSampling.
func (in *RateLimitSampling) DeepCopy() *RateLimitSampling {
	if in == nil {
		return nil
	}
	out := new(RateLimitSampling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule_HeaderOperationTemplate) DeepCopyInto(out *Rule_HeaderOperationTemplate) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule_HeaderOperationTemplate.
func (in *Rule_HeaderOperationTemplate) DeepCopy() *Rule_HeaderOperationTemplate {
	if in == nil {
		return nil
	}
	out := new(Rule_HeaderOperationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sampling) DeepCopyInto(out *Sampling) {
	*out = *in
	if in.Random != nil {
		in, out := &in.Random, &out.Random
		if *in == nil {
			*out = nil
		} else {
			*out = new(RandomSampling)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		if *in == nil {
			*out = nil
		} else {
			*out = new(RateLimitSampling)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sampling.
func (in *Sampling) DeepCopy() *Sampling {
	if in == nil {
		return nil
	}
	out := new(Sampling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeStamp) DeepCopyInto(out *TimeStamp) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.Timestamp)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeStamp.
func (in *TimeStamp) DeepCopy() *TimeStamp {
	if in == nil {
		return nil
	}
	out := new(TimeStamp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls) DeepCopyInto(out *Tls) {
	*out = *in
	if in.TokenSource == nil {
		out.TokenSource = nil
	} else {
		out.TokenSource = in.TokenSource.DeepCopyisTls_TokenSource()
	}
	if in.TokenType == nil {
		out.TokenType = nil
	} else {
		out.TokenType = in.TokenType.DeepCopyisTls_TokenType()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls.
func (in *Tls) DeepCopy() *Tls {
	if in == nil {
		return nil
	}
	out := new(Tls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls_AuthHeader_) DeepCopyInto(out *Tls_AuthHeader_) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls_AuthHeader_.
func (in *Tls_AuthHeader_) DeepCopy() *Tls_AuthHeader_ {
	if in == nil {
		return nil
	}
	out := new(Tls_AuthHeader_)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls_CustomHeader) DeepCopyInto(out *Tls_CustomHeader) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls_CustomHeader.
func (in *Tls_CustomHeader) DeepCopy() *Tls_CustomHeader {
	if in == nil {
		return nil
	}
	out := new(Tls_CustomHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls_Oauth) DeepCopyInto(out *Tls_Oauth) {
	*out = *in
	if in.Oauth != nil {
		in, out := &in.Oauth, &out.Oauth
		if *in == nil {
			*out = nil
		} else {
			*out = new(OAuth)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls_Oauth.
func (in *Tls_Oauth) DeepCopy() *Tls_Oauth {
	if in == nil {
		return nil
	}
	out := new(Tls_Oauth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tls_TokenPath) DeepCopyInto(out *Tls_TokenPath) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tls_TokenPath.
func (in *Tls_TokenPath) DeepCopy() *Tls_TokenPath {
	if in == nil {
		return nil
	}
	out := new(Tls_TokenPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Uri) DeepCopyInto(out *Uri) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Uri.
func (in *Uri) DeepCopy() *Uri {
	if in == nil {
		return nil
	}
	out := new(Uri)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value) DeepCopyInto(out *Value) {
	*out = *in
	if in.Value == nil {
		out.Value = nil
	} else {
		out.Value = in.Value.DeepCopyisValue_Value()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value.
func (in *Value) DeepCopy() *Value {
	if in == nil {
		return nil
	}
	out := new(Value)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_BoolValue) DeepCopyInto(out *Value_BoolValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_BoolValue.
func (in *Value_BoolValue) DeepCopy() *Value_BoolValue {
	if in == nil {
		return nil
	}
	out := new(Value_BoolValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_DnsNameValue) DeepCopyInto(out *Value_DnsNameValue) {
	*out = *in
	if in.DnsNameValue != nil {
		in, out := &in.DnsNameValue, &out.DnsNameValue
		if *in == nil {
			*out = nil
		} else {
			*out = new(DNSName)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_DnsNameValue.
func (in *Value_DnsNameValue) DeepCopy() *Value_DnsNameValue {
	if in == nil {
		return nil
	}
	out := new(Value_DnsNameValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_DoubleValue) DeepCopyInto(out *Value_DoubleValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_DoubleValue.
func (in *Value_DoubleValue) DeepCopy() *Value_DoubleValue {
	if in == nil {
		return nil
	}
	out := new(Value_DoubleValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_DurationValue) DeepCopyInto(out *Value_DurationValue) {
	*out = *in
	if in.DurationValue != nil {
		in, out := &in.DurationValue, &out.DurationValue
		if *in == nil {
			*out = nil
		} else {
			*out = new(Duration)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_DurationValue.
func (in *Value_DurationValue) DeepCopy() *Value_DurationValue {
	if in == nil {
		return nil
	}
	out := new(Value_DurationValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_EmailAddressValue) DeepCopyInto(out *Value_EmailAddressValue) {
	*out = *in
	if in.EmailAddressValue != nil {
		in, out := &in.EmailAddressValue, &out.EmailAddressValue
		if *in == nil {
			*out = nil
		} else {
			*out = new(EmailAddress)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_EmailAddressValue.
func (in *Value_EmailAddressValue) DeepCopy() *Value_EmailAddressValue {
	if in == nil {
		return nil
	}
	out := new(Value_EmailAddressValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_Int64Value) DeepCopyInto(out *Value_Int64Value) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_Int64Value.
func (in *Value_Int64Value) DeepCopy() *Value_Int64Value {
	if in == nil {
		return nil
	}
	out := new(Value_Int64Value)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_IpAddressValue) DeepCopyInto(out *Value_IpAddressValue) {
	*out = *in
	if in.IpAddressValue != nil {
		in, out := &in.IpAddressValue, &out.IpAddressValue
		if *in == nil {
			*out = nil
		} else {
			*out = new(IPAddress)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_IpAddressValue.
func (in *Value_IpAddressValue) DeepCopy() *Value_IpAddressValue {
	if in == nil {
		return nil
	}
	out := new(Value_IpAddressValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_StringValue) DeepCopyInto(out *Value_StringValue) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_StringValue.
func (in *Value_StringValue) DeepCopy() *Value_StringValue {
	if in == nil {
		return nil
	}
	out := new(Value_StringValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_TimestampValue) DeepCopyInto(out *Value_TimestampValue) {
	*out = *in
	if in.TimestampValue != nil {
		in, out := &in.TimestampValue, &out.TimestampValue
		if *in == nil {
			*out = nil
		} else {
			*out = new(TimeStamp)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_TimestampValue.
func (in *Value_TimestampValue) DeepCopy() *Value_TimestampValue {
	if in == nil {
		return nil
	}
	out := new(Value_TimestampValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Value_UriValue) DeepCopyInto(out *Value_UriValue) {
	*out = *in
	if in.UriValue != nil {
		in, out := &in.UriValue, &out.UriValue
		if *in == nil {
			*out = nil
		} else {
			*out = new(Uri)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Value_UriValue.
func (in *Value_UriValue) DeepCopy() *Value_UriValue {
	if in == nil {
		return nil
	}
	out := new(Value_UriValue)
	in.DeepCopyInto(out)
	return out
}
