// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/v1/config/client/api_spec.proto

package client // import "github.com/f4tq/istio-api-mod/mixer/v1/config/client"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/f4tq/istio-api-mod/mixer/v1"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for HTTPAPISpec
func (this *HTTPAPISpec) MarshalJSON() ([]byte, error) {
	str, err := ApiSpecMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for HTTPAPISpec
func (this *HTTPAPISpec) UnmarshalJSON(b []byte) error {
	return ApiSpecUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for HTTPAPISpecPattern
func (this *HTTPAPISpecPattern) MarshalJSON() ([]byte, error) {
	str, err := ApiSpecMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for HTTPAPISpecPattern
func (this *HTTPAPISpecPattern) UnmarshalJSON(b []byte) error {
	return ApiSpecUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for APIKey
func (this *APIKey) MarshalJSON() ([]byte, error) {
	str, err := ApiSpecMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for APIKey
func (this *APIKey) UnmarshalJSON(b []byte) error {
	return ApiSpecUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for HTTPAPISpecReference
func (this *HTTPAPISpecReference) MarshalJSON() ([]byte, error) {
	str, err := ApiSpecMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for HTTPAPISpecReference
func (this *HTTPAPISpecReference) UnmarshalJSON(b []byte) error {
	return ApiSpecUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for HTTPAPISpecBinding
func (this *HTTPAPISpecBinding) MarshalJSON() ([]byte, error) {
	str, err := ApiSpecMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for HTTPAPISpecBinding
func (this *HTTPAPISpecBinding) UnmarshalJSON(b []byte) error {
	return ApiSpecUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ApiSpecMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ApiSpecUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
