// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/v1/config/client/client_config.proto

package client // import "github.com/f4tq/istio-api-mod/mixer/v1/config/client"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/f4tq/istio-api-mod/mixer/v1"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for NetworkFailPolicy
func (this *NetworkFailPolicy) MarshalJSON() ([]byte, error) {
	str, err := ClientConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for NetworkFailPolicy
func (this *NetworkFailPolicy) UnmarshalJSON(b []byte) error {
	return ClientConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for ServiceConfig
func (this *ServiceConfig) MarshalJSON() ([]byte, error) {
	str, err := ClientConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for ServiceConfig
func (this *ServiceConfig) UnmarshalJSON(b []byte) error {
	return ClientConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for TransportConfig
func (this *TransportConfig) MarshalJSON() ([]byte, error) {
	str, err := ClientConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for TransportConfig
func (this *TransportConfig) UnmarshalJSON(b []byte) error {
	return ClientConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for HttpClientConfig
func (this *HttpClientConfig) MarshalJSON() ([]byte, error) {
	str, err := ClientConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for HttpClientConfig
func (this *HttpClientConfig) UnmarshalJSON(b []byte) error {
	return ClientConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for HttpClientConfig_ServiceConfigsEntry
func (this *HttpClientConfig_ServiceConfigsEntry) MarshalJSON() ([]byte, error) {
	str, err := ClientConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for HttpClientConfig_ServiceConfigsEntry
func (this *HttpClientConfig_ServiceConfigsEntry) UnmarshalJSON(b []byte) error {
	return ClientConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for TcpClientConfig
func (this *TcpClientConfig) MarshalJSON() ([]byte, error) {
	str, err := ClientConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for TcpClientConfig
func (this *TcpClientConfig) UnmarshalJSON(b []byte) error {
	return ClientConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ClientConfigMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ClientConfigUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
