// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/v1/config/client/quota.proto

package client // import "github.com/f4tq/istio-api-mod/mixer/v1/config/client"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaSpec
func (this *QuotaSpec) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaSpec
func (this *QuotaSpec) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaRule
func (this *QuotaRule) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaRule
func (this *QuotaRule) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for StringMatch
func (this *StringMatch) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for StringMatch
func (this *StringMatch) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for AttributeMatch
func (this *AttributeMatch) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for AttributeMatch
func (this *AttributeMatch) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for AttributeMatch_ClauseEntry
func (this *AttributeMatch_ClauseEntry) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for AttributeMatch_ClauseEntry
func (this *AttributeMatch_ClauseEntry) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Quota
func (this *Quota) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Quota
func (this *Quota) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaSpecBinding
func (this *QuotaSpecBinding) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaSpecBinding
func (this *QuotaSpecBinding) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for QuotaSpecBinding_QuotaSpecReference
func (this *QuotaSpecBinding_QuotaSpecReference) MarshalJSON() ([]byte, error) {
	str, err := QuotaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for QuotaSpecBinding_QuotaSpecReference
func (this *QuotaSpecBinding_QuotaSpecReference) UnmarshalJSON(b []byte) error {
	return QuotaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	QuotaMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	QuotaUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
