// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mixer/v1/config/client/service.proto

package client // import "github.com/f4tq/istio-api-mod/mixer/v1/config/client"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for IstioService
func (this *IstioService) MarshalJSON() ([]byte, error) {
	str, err := ServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for IstioService
func (this *IstioService) UnmarshalJSON(b []byte) error {
	return ServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for IstioService_LabelsEntry
func (this *IstioService_LabelsEntry) MarshalJSON() ([]byte, error) {
	str, err := ServiceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for IstioService_LabelsEntry
func (this *IstioService_LabelsEntry) UnmarshalJSON(b []byte) error {
	return ServiceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ServiceMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ServiceUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
