// +build !ignore_autogenerated

// Copyright 2019 Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package client

import (
	v1 "github.com/f4tq/istio-api-mod/mixer/v1"
	types "github.com/gogo/protobuf/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKey) DeepCopyInto(out *APIKey) {
	*out = *in
	if in.Key == nil {
		out.Key = nil
	} else {
		out.Key = in.Key.DeepCopyisAPIKey_Key()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKey.
func (in *APIKey) DeepCopy() *APIKey {
	if in == nil {
		return nil
	}
	out := new(APIKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKey_Cookie) DeepCopyInto(out *APIKey_Cookie) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKey_Cookie.
func (in *APIKey_Cookie) DeepCopy() *APIKey_Cookie {
	if in == nil {
		return nil
	}
	out := new(APIKey_Cookie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKey_Header) DeepCopyInto(out *APIKey_Header) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKey_Header.
func (in *APIKey_Header) DeepCopy() *APIKey_Header {
	if in == nil {
		return nil
	}
	out := new(APIKey_Header)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKey_Query) DeepCopyInto(out *APIKey_Query) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKey_Query.
func (in *APIKey_Query) DeepCopy() *APIKey_Query {
	if in == nil {
		return nil
	}
	out := new(APIKey_Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeMatch) DeepCopyInto(out *AttributeMatch) {
	*out = *in
	if in.Clause != nil {
		in, out := &in.Clause, &out.Clause
		*out = make(map[string]*StringMatch, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = new(StringMatch)
				val.DeepCopyInto((*out)[key])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeMatch.
func (in *AttributeMatch) DeepCopy() *AttributeMatch {
	if in == nil {
		return nil
	}
	out := new(AttributeMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAPISpec.
func (in *HTTPAPISpec) DeepCopy() *HTTPAPISpec {
	if in == nil {
		return nil
	}
	out := new(HTTPAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAPISpecBinding.
func (in *HTTPAPISpecBinding) DeepCopy() *HTTPAPISpecBinding {
	if in == nil {
		return nil
	}
	out := new(HTTPAPISpecBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAPISpecPattern) DeepCopyInto(out *HTTPAPISpecPattern) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Pattern == nil {
		out.Pattern = nil
	} else {
		out.Pattern = in.Pattern.DeepCopyisHTTPAPISpecPattern_Pattern()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAPISpecPattern.
func (in *HTTPAPISpecPattern) DeepCopy() *HTTPAPISpecPattern {
	if in == nil {
		return nil
	}
	out := new(HTTPAPISpecPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAPISpecPattern_Regex) DeepCopyInto(out *HTTPAPISpecPattern_Regex) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAPISpecPattern_Regex.
func (in *HTTPAPISpecPattern_Regex) DeepCopy() *HTTPAPISpecPattern_Regex {
	if in == nil {
		return nil
	}
	out := new(HTTPAPISpecPattern_Regex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAPISpecPattern_UriTemplate) DeepCopyInto(out *HTTPAPISpecPattern_UriTemplate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAPISpecPattern_UriTemplate.
func (in *HTTPAPISpecPattern_UriTemplate) DeepCopy() *HTTPAPISpecPattern_UriTemplate {
	if in == nil {
		return nil
	}
	out := new(HTTPAPISpecPattern_UriTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAPISpecReference) DeepCopyInto(out *HTTPAPISpecReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAPISpecReference.
func (in *HTTPAPISpecReference) DeepCopy() *HTTPAPISpecReference {
	if in == nil {
		return nil
	}
	out := new(HTTPAPISpecReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpClientConfig) DeepCopyInto(out *HttpClientConfig) {
	*out = *in
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		if *in == nil {
			*out = nil
		} else {
			*out = new(TransportConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ServiceConfigs != nil {
		in, out := &in.ServiceConfigs, &out.ServiceConfigs
		*out = make(map[string]*ServiceConfig, len(*in))
		for key, val := range *in {
			if val == nil {
				(*out)[key] = nil
			} else {
				(*out)[key] = new(ServiceConfig)
				val.DeepCopyInto((*out)[key])
			}
		}
	}
	if in.MixerAttributes != nil {
		in, out := &in.MixerAttributes, &out.MixerAttributes
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ForwardAttributes != nil {
		in, out := &in.ForwardAttributes, &out.ForwardAttributes
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpClientConfig.
func (in *HttpClientConfig) DeepCopy() *HttpClientConfig {
	if in == nil {
		return nil
	}
	out := new(HttpClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioService) DeepCopyInto(out *IstioService) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioService.
func (in *IstioService) DeepCopy() *IstioService {
	if in == nil {
		return nil
	}
	out := new(IstioService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkFailPolicy) DeepCopyInto(out *NetworkFailPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkFailPolicy.
func (in *NetworkFailPolicy) DeepCopy() *NetworkFailPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkFailPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quota) DeepCopyInto(out *Quota) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quota.
func (in *Quota) DeepCopy() *Quota {
	if in == nil {
		return nil
	}
	out := new(Quota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaRule) DeepCopyInto(out *QuotaRule) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]*AttributeMatch, len(*in))
		for i := range *in {
			if (*in)[i] == nil {
				(*out)[i] = nil
			} else {
				(*out)[i] = new(AttributeMatch)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = make([]*Quota, len(*in))
		for i := range *in {
			if (*in)[i] == nil {
				(*out)[i] = nil
			} else {
				(*out)[i] = new(Quota)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaRule.
func (in *QuotaRule) DeepCopy() *QuotaRule {
	if in == nil {
		return nil
	}
	out := new(QuotaRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpec.
func (in *QuotaSpec) DeepCopy() *QuotaSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpecBinding.
func (in *QuotaSpecBinding) DeepCopy() *QuotaSpecBinding {
	if in == nil {
		return nil
	}
	out := new(QuotaSpecBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSpecBinding_QuotaSpecReference) DeepCopyInto(out *QuotaSpecBinding_QuotaSpecReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpecBinding_QuotaSpecReference.
func (in *QuotaSpecBinding_QuotaSpecReference) DeepCopy() *QuotaSpecBinding_QuotaSpecReference {
	if in == nil {
		return nil
	}
	out := new(QuotaSpecBinding_QuotaSpecReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.MixerAttributes != nil {
		in, out := &in.MixerAttributes, &out.MixerAttributes
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.HttpApiSpec != nil {
		in, out := &in.HttpApiSpec, &out.HttpApiSpec
		*out = make([]*HTTPAPISpec, len(*in))
		for i := range *in {
			if (*in)[i] == nil {
				(*out)[i] = nil
			} else {
				(*out)[i] = new(HTTPAPISpec)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.QuotaSpec != nil {
		in, out := &in.QuotaSpec, &out.QuotaSpec
		*out = make([]*QuotaSpec, len(*in))
		for i := range *in {
			if (*in)[i] == nil {
				(*out)[i] = nil
			} else {
				(*out)[i] = new(QuotaSpec)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.NetworkFailPolicy != nil {
		in, out := &in.NetworkFailPolicy, &out.NetworkFailPolicy
		if *in == nil {
			*out = nil
		} else {
			*out = new(NetworkFailPolicy)
			**out = **in
		}
	}
	if in.ForwardAttributes != nil {
		in, out := &in.ForwardAttributes, &out.ForwardAttributes
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	*out = *in
	if in.MatchType == nil {
		out.MatchType = nil
	} else {
		out.MatchType = in.MatchType.DeepCopyisStringMatch_MatchType()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch_Exact) DeepCopyInto(out *StringMatch_Exact) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch_Exact.
func (in *StringMatch_Exact) DeepCopy() *StringMatch_Exact {
	if in == nil {
		return nil
	}
	out := new(StringMatch_Exact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch_Prefix) DeepCopyInto(out *StringMatch_Prefix) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch_Prefix.
func (in *StringMatch_Prefix) DeepCopy() *StringMatch_Prefix {
	if in == nil {
		return nil
	}
	out := new(StringMatch_Prefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch_Regex) DeepCopyInto(out *StringMatch_Regex) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch_Regex.
func (in *StringMatch_Regex) DeepCopy() *StringMatch_Regex {
	if in == nil {
		return nil
	}
	out := new(StringMatch_Regex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcpClientConfig) DeepCopyInto(out *TcpClientConfig) {
	*out = *in
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		if *in == nil {
			*out = nil
		} else {
			*out = new(TransportConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.MixerAttributes != nil {
		in, out := &in.MixerAttributes, &out.MixerAttributes
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ConnectionQuotaSpec != nil {
		in, out := &in.ConnectionQuotaSpec, &out.ConnectionQuotaSpec
		if *in == nil {
			*out = nil
		} else {
			*out = (*in).DeepCopy()
		}
	}
	if in.ReportInterval != nil {
		in, out := &in.ReportInterval, &out.ReportInterval
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.Duration)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcpClientConfig.
func (in *TcpClientConfig) DeepCopy() *TcpClientConfig {
	if in == nil {
		return nil
	}
	out := new(TcpClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportConfig) DeepCopyInto(out *TransportConfig) {
	*out = *in
	if in.NetworkFailPolicy != nil {
		in, out := &in.NetworkFailPolicy, &out.NetworkFailPolicy
		if *in == nil {
			*out = nil
		} else {
			*out = new(NetworkFailPolicy)
			**out = **in
		}
	}
	if in.StatsUpdateInterval != nil {
		in, out := &in.StatsUpdateInterval, &out.StatsUpdateInterval
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.Duration)
			**out = **in
		}
	}
	if in.AttributesForMixerProxy != nil {
		in, out := &in.AttributesForMixerProxy, &out.AttributesForMixerProxy
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.Attributes)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportConfig.
func (in *TransportConfig) DeepCopy() *TransportConfig {
	if in == nil {
		return nil
	}
	out := new(TransportConfig)
	in.DeepCopyInto(out)
	return out
}
