// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mesh/v1alpha1/config.proto

package v1alpha1 // import "github.com/f4tq/istio-api-mod/mesh/v1alpha1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/f4tq/istio-api-mod/networking/v1alpha3"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for MeshConfig
func (this *MeshConfig) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for MeshConfig
func (this *MeshConfig) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for MeshConfig_OutboundTrafficPolicy
func (this *MeshConfig_OutboundTrafficPolicy) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for MeshConfig_OutboundTrafficPolicy
func (this *MeshConfig_OutboundTrafficPolicy) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for ConfigSource
func (this *ConfigSource) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for ConfigSource
func (this *ConfigSource) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for LocalityLoadBalancerSetting
func (this *LocalityLoadBalancerSetting) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for LocalityLoadBalancerSetting
func (this *LocalityLoadBalancerSetting) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for LocalityLoadBalancerSetting_Distribute
func (this *LocalityLoadBalancerSetting_Distribute) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for LocalityLoadBalancerSetting_Distribute
func (this *LocalityLoadBalancerSetting_Distribute) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for LocalityLoadBalancerSetting_Distribute_ToEntry
func (this *LocalityLoadBalancerSetting_Distribute_ToEntry) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for LocalityLoadBalancerSetting_Distribute_ToEntry
func (this *LocalityLoadBalancerSetting_Distribute_ToEntry) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for LocalityLoadBalancerSetting_Failover
func (this *LocalityLoadBalancerSetting_Failover) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for LocalityLoadBalancerSetting_Failover
func (this *LocalityLoadBalancerSetting_Failover) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ConfigMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ConfigUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
