// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mesh/v1alpha1/proxy.proto

package v1alpha1 // import "github.com/f4tq/istio-api-mod/mesh/v1alpha1"

import bytes "bytes"
import github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for Tracing
func (this *Tracing) MarshalJSON() ([]byte, error) {
	str, err := ProxyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Tracing
func (this *Tracing) UnmarshalJSON(b []byte) error {
	return ProxyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ProxyMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ProxyUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
